/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function execvp(file: string, args: Array<string>): void
export declare function doNotCloseOnExit(fd: number): void
